### ISSUE TITLE
$data returns everything with $data

### ISSUE THREAD

**Issue by kevinvennitti** [lukaskleinschmidt/kirby-snippet-controller#1]
Hi!

I am using a snippet controller to fetch snippet data and get `mydata`:
```php
snippet('mysnippet', ['mydata' => 'my value']);
``` 

```php
// mysnippet.controller.php

<?php

return function ($site, $data) {
  print_r($data);

  return [];
};
``` 

`$data` should be: 
```php
Array ( 
  'mydata' => 'my value'
)
```

Instead, `$data` returns: 
```php
Array ( 
  'kirby' => Kirby\Cms\App Object ( … ), 
  'site' => Kirby\Cms\Site Object ( … ),
  'pages' => Kirby\Cms\Pages Object ( … ),
  'page' => Kirby\Cms\Page Object ( … ),
  'mydata' => 'my value',
)
```

Am I using it wrong? :)

**Comment by lukaskleinschmidt** [comment]
The docs are probably not as clear on this part. You get all variables that will be available in your snippet. Actually this is nothing I added specifically. If you would replace the `snippets` component yourself you would always get at least the `kirby`, `site`, `pages` and `page` objects at [this point](https://github.com/lukaskleinschmidt/kirby-snippet-controller/blob/main/index.php#L12) as those are the default variables that are always available in snippets.

Filtering out these variables also makes no sense (at least for the plugin) since you can override any of these default variables as well.
```php
snippet('mysnippet', ['page' => null]);
```

**Comment by kevinvennitti** [comment]
That's clear, thanks!

(and thanks for the plugin!)

**Comment by lukaskleinschmidt** [comment]
Actually you issue got me thinking. @kevinvennitti what is your actual use case for the `$data` array?
Do you use it to actually do a loop over it or do you just need one or more values from the array?

I think it would actually make more sense to pass the `$data` as possible args so you could do something like this. This would also help to properly typehint arguments:

```php
<?php

return function (Site $site, mixed $mydata = null, TargetPage $target)
{
    return [
        //
    ];
};
```
